---
title: "linear_models"
output: github_document
---

```{r, include = FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

# Model Fitting

import and clean data
```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighborhood, room_type)
```

fit model
```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
# R converts character into factor... factor order is determined by alphabetical order

summary(fit)

fit %>%
  broom::tidy() %>%
  mutate(
    term = str_replace(term, "borough", "Borough: ")
  ) %>%
  select(term, estimate, p.value) %>%
  knitr::kable(digits = 2)
```

Let's change reference category by changing factor order by frequency
```{r}
fit <-
  nyc_airbnb %>%
  mutate(
    borough = fct_infreq(borough)
  ) %>%
  lm(price ~ stars + borough, data = .)

fit %>%
  broom::tidy() %>%
  mutate(
    term = str_replace(term, "borough", "Borough: ")
  ) %>%
  select(term, estimate, p.value) %>%
  knitr::kable(digits = 2)

# finding AIC
fit %>%
  broom::glance() %>%
  select(AIC)
  
```

## Regression Diagnostics

```{r}
# add residuals into original dataset
modelr::add_residuals(nyc_airbnb, fit) %>%
  ggplot(aes(x = stars, y = resid)) + 
  geom_point()
# no constant variance as we have many more variance in certain stars


nyc_airbnb %>%
  modelr::add_residuals(fit) %>%
  ggplot(aes(x = borough, y = resid)) + 
  geom_violin() +
  ylim(-250, 250)
# skewed distribution... mean below 0
# also... take note our sample size is big so are our estimates valid? maybe, we will find out

```

## Hypothesis testing

one coefficient (let's say `stars`)... assuming model assumptions are met
```{r}
fit %>%
  broom::tidy()


fit_null = lm(price ~ stars, data = nyc_airbnb)
fit_alt = lm(price ~ stars + borough, data = nyc_airbnb)

anova(fit_null, fit_alt) %>%
  broom::tidy()
```


## Room type by borough

Interactions...?
```{r}
fit <-
  nyc_airbnb %>%
  lm(price ~ stars + borough * room_type, data = .)

fit %>%
  broom::tidy()

```

So can we fit models by borough...?
```{r}
nyc_airbnb %>%
  nest(df = -borough) %>%
  mutate(
    models = map(.x = df, ~lm(price ~ stars + room_type, data = .x)),
    results = map(models, broom::tidy)
  ) %>%
  select(borough, results) %>%
  unnest(results)
```

